name: ğŸš€ Otomatik YayÄ±nla (FTP)

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: ğŸšš DosyalarÄ± GÃ¶nder
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Kodu Al
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: ğŸ“‚ FTP ile YÃ¼kle
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Sadece GitHub'daki dosyalarÄ± gÃ¶nderir (.gitignore'dakileri atlarsa bile gÃ¼venli olur)
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
